In [1]:
import numpy as np

In [2]:
# create an array

a = np.array([34, 43, 41, 56, 28, 12])

In [3]:
print(a)

[34 43 41 56 28 12]


In [4]:
a

array([34, 43, 41, 56, 28, 12])

In [5]:
b = np.array([34, 43, 41, 56, 28, 12, 12.23])

In [6]:
b

array([34.  , 43.  , 41.  , 56.  , 28.  , 12.  , 12.23])

In [7]:
b = np.array([34, 43, 41, 56, 28, 12, 12.23, 'Aditya'])

In [8]:
b

array(['34', '43', '41', '56', '28', '12', '12.23', 'Aditya'],
      dtype='<U32')

In [9]:
a

array([34, 43, 41, 56, 28, 12])

In [10]:
a[1]

43

In [11]:
a.dtype

dtype('int64')

In [12]:
b.dtype

dtype('<U32')

In [13]:
a.shape

(6,)

In [14]:
a.ndim

1

In [15]:
a

array([34, 43, 41, 56, 28, 12])

In [16]:
a + 10

array([44, 53, 51, 66, 38, 22])

In [17]:
a * 2

array([ 68,  86,  82, 112,  56,  24])

In [18]:
# linear equation
new = a * 3.5 + 10.3

In [19]:
new

array([129.3, 160.8, 153.8, 206.3, 108.3,  52.3])

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(4, 10)

array([4, 5, 6, 7, 8, 9])

In [22]:
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

In [46]:
np.arange(-5, 5, 0.25)

array([-5.  , -4.75, -4.5 , -4.25, -4.  , -3.75, -3.5 , -3.25, -3.  ,
       -2.75, -2.5 , -2.25, -2.  , -1.75, -1.5 , -1.25, -1.  , -0.75,
       -0.5 , -0.25,  0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,
        1.75,  2.  ,  2.25,  2.5 ,  2.75,  3.  ,  3.25,  3.5 ,  3.75,
        4.  ,  4.25,  4.5 ,  4.75])

In [48]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [54]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [56]:
arr.shape

(4, 3)

In [58]:
arr.size

12

In [60]:
arr.ndim

2

In [62]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [64]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [66]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
arr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [70]:
arr.reshape(2,-1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [72]:
arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [74]:
arr.reshape(3,4,-1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

In [76]:
a

array([34, 43, 41, 56, 28, 12])

In [80]:
a[1:4]

array([43, 41, 56])

In [82]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [87]:
arr[1:3, 0:2]

array([[4, 5],
       [7, 8]])

In [89]:
arr[1:, 1:]

array([[ 5,  6],
       [ 8,  9],
       [11, 12]])

In [95]:
a = np.array([[1,2,3], [4,5,6], [8,9,4]])
b = np.array([[3,5,2], [5,4,2], [9,2,6]])

In [97]:
a,b

(array([[1, 2, 3],
        [4, 5, 6],
        [8, 9, 4]]),
 array([[3, 5, 2],
        [5, 4, 2],
        [9, 2, 6]]))

In [99]:
a - b

array([[-2, -3,  1],
       [-1,  1,  4],
       [-1,  7, -2]])

In [101]:
a + b

array([[ 4,  7,  5],
       [ 9,  9,  8],
       [17, 11, 10]])

In [103]:
a / b

array([[0.33333333, 0.4       , 1.5       ],
       [0.8       , 1.25      , 3.        ],
       [0.88888889, 4.5       , 0.66666667]])

In [105]:
np.dot(a, b)

array([[ 40,  19,  24],
       [ 91,  52,  54],
       [105,  84,  58]])

In [107]:
a @ b  # dot product

array([[ 40,  19,  24],
       [ 91,  52,  54],
       [105,  84,  58]])

In [109]:
np.linalg.inv(a)

array([[-1.88888889,  1.05555556, -0.16666667],
       [ 1.77777778, -1.11111111,  0.33333333],
       [-0.22222222,  0.38888889, -0.16666667]])

In [111]:
np.linalg.det(a)

17.999999999999996

In [113]:
a.T

array([[1, 4, 8],
       [2, 5, 9],
       [3, 6, 4]])

In [115]:
z = np.array([3,3,3, 4,4,5,2,1])

In [117]:
np.unique(z)

array([1, 2, 3, 4, 5])

In [119]:
z.mean()

3.125

In [121]:
np.mean(z)

3.125

In [123]:
np.sort(z)

array([1, 2, 3, 3, 3, 4, 4, 5])

In [125]:
np.std(z)

1.165922381636102

In [129]:
'''
Create a NumPy array containing the numbers from 1 to 10. 
Reshape this array into a 2x5 matrix. Then, calculate the mean of each row.
''';

In [131]:
arr1 = np.arange(1,11)

In [133]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
arr1 = arr1.reshape(2,5)

In [137]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [139]:
np.mean(arr1[0,:])

3.0

In [141]:
np.mean(arr1[1,:])

8.0

In [143]:
means = np.mean(arr1, axis = 1)

In [145]:
means

array([3., 8.])

#### random

In [148]:
np.random.rand(2,3)
# creates array with values 0 to 1

array([[0.33346034, 0.62641174, 0.02421792],
       [0.49565182, 0.56975013, 0.10946417]])

In [150]:
np.random.rand(2,3)

array([[0.85674723, 0.1623653 , 0.66882738],
       [0.3557625 , 0.18830174, 0.35253032]])

In [152]:
np.random.randint(10, 30, size = 5)
# generate random 5 integers between 10 to 30

array([28, 23, 27, 10, 24])

In [156]:
np.random.uniform(10, 30, size = (2,5))

array([[22.3752228 , 11.20115474, 23.5089075 , 20.09388658, 21.40231083],
       [22.07022427, 19.56020239, 29.10056675, 22.86550987, 27.36838824]])

In [158]:
# choosing randomly from values

color = ['orange', 'gree', 'purple', 'black', 'white']

In [166]:
np.random.choice(color, size = 1)

array(['orange'], dtype='<U6')

In [174]:
# to create normal distributed
# mean = 0, std = 1
a = np.random.randn(2,3)
a

array([[ 0.82646021,  0.97860359, -0.28543003],
       [ 0.25134851,  0.01940133, -0.1009332 ]])

In [190]:
# seed
np.random.seed(10)
np.random.rand(2,3)

array([[0.77132064, 0.02075195, 0.63364823],
       [0.74880388, 0.49850701, 0.22479665]])